### PR TITLE
add inline extmark support after neovim/neovim#20130 merged

### PR DESCRIPTION
**Pull request by TwIStOy**

### CODE REVIEW

**Comment by p00f** [comment]
Should we just wait for this to be added to neovim instead? Inlay hints are part of the spec

**Comment by TwIStOy** [comment]
Updated!

**Comment by p00f** [comment]
> The inline virt text feature has been merged into neovim's master. I think we can use this directly?

I was thinking of waiting for neovim to add inlay hints in their lsp implementation - it will happen eventually

**Comment by TwIStOy** [comment]
This issue neovim/neovim#18086?

**Comment by p00f** [comment]
Yes, see this comment on the issue - https://github.com/neovim/neovim/issues/18086#issuecomment-1095937211

**Comment by p00f** [comment]
I'll add something rudimentary for now

**Comment by p00f** [comment]
Sorry, I can't merge this as I had something simpler in mind - which I pushed, try it out

**Pull request closed without merging**
